from dataclasses import dataclass
from datetime import date
from typing import Self

from dateutil.rrule import rrule
from stockholm import Money


@dataclass
class Transaction:
    """A single transaction record."""

    date: date
    amount: Money
    description: str
    parent: "RecurringTransaction | Transaction | None" = None

    def __lt__(self, other: Self):
        """Compare transactions based on their date for ordering."""
        return self.date < other.date


@dataclass
class RecurringTransaction:
    """
    A transaction that repeats on a schedule described by a
    `dateutil.rrule.rrule`.
    """

    rrule: rrule
    amount: Money
    description: str

    def __iter__(self):
        """
        Yield transactions generated by the recurring rule, each with the
        specified amount and description, and link them to this recurring
        transaction as their parent.
        """
        for next in self.rrule:
            yield Transaction(
                date=next.date(),
                amount=self.amount,
                description=self.description,
                parent=self,
            )
